# Generated by Django 6.1.1 on 2026-09-11 04:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoadmapItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap_items', to='academics.grade')),
            ],
            options={
                'ordering': ['grade__number', 'order'],
            },
        ),
    ]
