# Generated by Django 6.1.1 on 2026-09-11 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MealAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('lunch', "Tushlik uchun qo'shimcha"), ('snack', "Choy vaqti uchun qo'shimcha")], max_length=10)),
                ('text', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=1)),
            ],
            options={
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='MealDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_number', models.PositiveSmallIntegerField(unique=True)),
                ('day_label', models.CharField(blank=True, max_length=30)),
            ],
            options={
                'ordering': ['day_number'],
            },
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('lunch', 'Tushlik'), ('snack', 'Choy vaqti')], max_length=10)),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('name', models.CharField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='meals/')),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='meals.mealday')),
            ],
            options={
                'ordering': ['day__day_number', 'category', 'order'],
            },
        ),
    ]
