# Generated by Django 6.1.1 on 2026-09-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('is_published', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(default='Roziy Xalqaro Xususiy Maktabi', max_length=255)),
                ('tagline', models.CharField(default="Bilim va tarbiya - bizning yo'limiz, rozi ota-ona va baxtli o'quvchi - NATIJAMIZ!", max_length=500)),
                ('since_year', models.PositiveSmallIntegerField(default=2026)),
                ('phone', models.CharField(default='+998 97 751 00 65', max_length=50)),
                ('instagram_url', models.URLField(blank=True, default='https://www.instagram.com/roziy_maktabi/')),
                ('region', models.CharField(default='Xorazm viloyati', max_length=255)),
                ('district', models.CharField(default='Shovot tumani', max_length=255)),
                ('address_note', models.CharField(default="Today ta'lim markazi yonida (Shovot pochta ro'parasi)", max_length=500)),
                ('grades_offered', models.CharField(default='1-9-sinflar', max_length=100)),
                ('monthly_tuition', models.DecimalField(decimal_places=2, default=1990000, max_digits=12)),
                ('license_number', models.CharField(blank=True, default='1839743', max_length=100)),
                ('license_holder_name', models.CharField(blank=True, default='RAZIY XALQARO MAKTABI MChJ', max_length=255)),
                ('license_activity_type', models.CharField(blank=True, default="Umumiy o'rta ta'lim xizmatlari", max_length=255)),
                ('license_image_front', models.ImageField(blank=True, null=True, upload_to='license/')),
                ('license_image_back', models.ImageField(blank=True, null=True, upload_to='license/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Sayt sozlamalari',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
    ]
