# Generated by Django 6.1.1 on 2026-09-11 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(max_length=150)),
                ('role', models.CharField(default='Ota-ona', max_length=100)),
                ('text_quote', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True, help_text='Instagram/YouTube link, if embedding externally')),
                ('video_file', models.FileField(blank=True, null=True, upload_to='testimonials/')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='testimonials/photos/')),
                ('order', models.PositiveSmallIntegerField(default=1)),
                ('is_published', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order', '-id'],
            },
        ),
    ]
