# Generated by Django 6.1.1 on 2026-09-11 04:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child_full_name', models.CharField(max_length=255)),
                ('child_birth_date', models.DateField(blank=True, null=True)),
                ('parent_full_name', models.CharField(max_length=255)),
                ('parent_phone', models.CharField(max_length=50)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('reviewing', "Ko'rib chiqilmoqda"), ('accepted', 'Qabul qilindi'), ('rejected', 'Rad etildi')], default='new', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('grade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.grade')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
