# Generated by Django 6.1.1 on 2026-09-11 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='status_note',
            field=models.TextField(blank=True, help_text="Ota-onaga ko'rinadigan qisqa izoh, masalan: 'Hujjatlaringiz tekshirilmoqda, 2 kun ichida qo'ng'iroq qilamiz.'"),
        ),
        migrations.AddField(
            model_name='application',
            name='tracking_code',
            field=models.CharField(blank=True, editable=False, help_text='Avtomatik yaratiladi. Ota-ona shu kod orqali ariza holatini tekshiradi.', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='application',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
